Devise
Hombre2014/RoR-blog pull request #10
Opened 2022-04-12 17:47 UTC by Hombre2014

All the requirements for this phase of the project have been implemented.

### Project requirements
- Remove `current_user` method in `ApplicationController`, devise will provide us with one.
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

2022-04-12 23:03 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @Hombre2014 + @KayLemba👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct Github Flow.
✅ Devise has been installed and setup.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

![lets-try-this-again-lauren-webber](https://user-images.githubusercontent.com/4247740/163068377-e7cb0b58-0829-457a-8a25-41e77fa63d97.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-12 23:03 UTC, Cathella commented on app/models/post.rb
> +  # validates :likes_counter, numericality: { only_integer: true, greater_than: -1 }
- [x] Please go on and delete the commented out code if it is no longer required. It helps in keeping your code clean and readable

2022-04-12 23:03 UTC, Cathella commented on app/views/devise/sessions/new.html.erb
> +
- [x] I am suggesting centering the forms to match the wireframes. For example

```
form {
    width: 50%;
    margin: 0 auto;
}

input {
    width: 100%;
}
```

2022-04-13 07:39 UTC, Hombre2014 commented
Thanks for your suggestions.

2022-04-13 09:01 UTC, Hombre2014 commented
All of the requested changes have been implemented.

2022-04-13 09:45 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Hombre2014,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-13 10:00 UTC, merged